//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class RoleDto
    {
        
        //Default Constructor
        public RoleDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<RoleDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.Id).NotNull();
                RuleFor(x => x.Name).MaximumLength(50).NotEmpty();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Role Dto to Role EF Model
        /// </summary>
        /// <returns>Role EF model</returns>
        public Role ToEFModel()
        {
            var model = new Role();
            model.Id = this.Id;
            model.Name = this.Name;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Role Entity Model
        /// </summary>
        /// <param name="model">Role model</param>
        /// <returns>Role Dto</returns>
        public static RoleDto FromEFModel(Role model)
        {
            if(model == null) return null;
            var dto = new RoleDto();
            dto.Id = model.Id;
            dto.Name = model.Name;
            return dto;
        }
    
    
        public int Id { get; set; }
        public string Name { get; set; }
    }
}
