//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    using FluentValidation.Internal;
    using FluentValidation.Resources;
    using FluentValidation.Results;
    using FluentValidation;
    using FluentValidation.Validators;
    
     public partial class StudentDto
    {
        
        //Default Constructor
        public StudentDto(){}
        
        public  class AbstractValidatorEF : AbstractValidator<StudentDto>
        {
            public AbstractValidatorEF()
            {
              SetValidationRules();
            }
            
            public virtual void SetValidationRules()
            {
                RuleFor(x => x.StudentID).NotNull();
                RuleFor(x => x.Name).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Email).MaximumLength(50).NotEmpty();
                RuleFor(x => x.Phone).MaximumLength(50).NotEmpty();
               
            }
       
        }
    
        
        
        
        /// <summary>
        /// Converts Student Dto to Student EF Model
        /// </summary>
        /// <returns>Student EF model</returns>
        public Student ToEFModel()
        {
            var model = new Student();
            model.StudentID = this.StudentID;
            model.Name = this.Name;
            model.Email = this.Email;
            model.Phone = this.Phone;
            return model;
        }
    
    
        // <summary>
        /// Creates a Dto from a Student Entity Model
        /// </summary>
        /// <param name="model">Student model</param>
        /// <returns>Student Dto</returns>
        public static StudentDto FromEFModel(Student model)
        {
            if(model == null) return null;
            var dto = new StudentDto();
            dto.StudentID = model.StudentID;
            dto.Name = model.Name;
            dto.Email = model.Email;
            dto.Phone = model.Phone;
            return dto;
        }
    
    
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
